#!/usr/bin/env zsh

# Test script to reproduce sshman's file creation behavior

# Test sync directory
SYNC_DIR='/Users/christophereller/Library/Mobile Documents/com~apple~CloudDocs/sshman'

echo "Testing sshman file creation with SYNC_DIR: $SYNC_DIR"
echo ""

# Create directories (same as sshman)
echo "Creating directories..."
mkdir -p "$SYNC_DIR/Identities"
if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to create Identities directory"
    exit 1
fi

touch "$SYNC_DIR/known_hosts"
if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to create known_hosts file"
    exit 1
fi

# Create the synced config file (same as sshman)
synced_config="$SYNC_DIR/config"
echo "Creating synced config at: $synced_config"

{
    echo "# SSH Key Manager Configuration"
    echo "# Generated by sshman"
    echo ""
    echo "# Cloud-synced known_hosts file"
    echo "UserKnownHostsFile $SYNC_DIR/known_hosts ~/.ssh/known_hosts"
    echo ""
    echo "# Default identity files location"
    echo "IdentityFile $SYNC_DIR/Identities/id_ed25519"
    echo "IdentityFile $SYNC_DIR/Identities/id_rsa"
    echo "IdentityFile $SYNC_DIR/Identities/id_ecdsa"
    echo ""
    echo "# SSH Agent configuration (macOS)"
    echo "AddKeysToAgent yes"
    echo "UseKeychain yes"
} > "$synced_config"

if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to write to $synced_config"
    exit 1
fi

chmod 600 "$synced_config"
if [[ $? -ne 0 ]]; then
    echo "ERROR: Failed to chmod $synced_config"
    exit 1
fi

echo ""
echo "Success! Checking created files:"
echo ""
echo "Directory contents:"
ls -la "$SYNC_DIR"
echo ""
echo "Config file contents:"
cat "$SYNC_DIR/config"